databases:
  - name: blog-db
    databaseName: blog_db
    user: blog_user
    plan: free

services:
  - type: web
    name: laravel-blog
    runtime: docker
    plan: free
    startCommand: "vendor/bin/heroku-php-apache2 public/"
    envVars:
      - key: APP_NAME
        value: BlogHub
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://laravel-blog.onrender.com
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: blog-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: blog-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: blog-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: blog-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: blog-db
          property: password
